# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  database: todo_development
  host: localhost

test:
  adapter: postgresql
  database: todo_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: todo_production
  pool: 5

